// data/products.js
const products = [
  {
    id: 1,
    name: "Organic Tomatoes",
    category: "Vegetables",
    price: 500,
    originalPrice: 500,
    unit: "per Kg",
    image: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?auto=format&fit=crop&q=80&w=600",
    seller: "Green Valley Co.",
    location: "Musanze",
    rating: 4.9,
    reviews: 218,
    sold: 156,
    inStock: true,
    isNew: true,
    discount: 0,
    description: "Premium organic tomatoes, fresh from Musanze farms. Perfect for salads, sauces, and healthy meals."
  },
  {
    id: 2,
    name: "Irish Potatoes",
    category: "Vegetables",
    price: 250,
    originalPrice: 300,
    unit: "per Kg",
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=600",
    seller: "Highland Farms",
    location: "Rubavu",
    rating: 4.7,
    reviews: 92,
    sold: 203,
    inStock: true,
    isNew: false,
    discount: 17,
    description: "High-quality Irish potatoes, rich in nutrients and perfect for boiling, frying, or baking."
  },
  {
    id: 3,
    name: "Premium Bananas",
    category: "Fruits",
    price: 2000,
    originalPrice: 2000,
    unit: "per Bunch",
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&q=80&w=600",
    seller: "Banana Hub",
    location: "Nyagatare",
    rating: 4.8,
    reviews: 178,
    sold: 234,
    inStock: true,
    isNew: false,
    discount: 0,
    description: "Sweet, ripe bananas sourced directly from Nyagatare farms. Ideal for snacking or smoothies."
  },
  {
    id: 4,
    name: "Fresh Mangoes",
    category: "Fruits",
    price: 1500,
    originalPrice: 1800,
    unit: "per Kg",
    image: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&q=80&w=600",
    seller: "Tropical Farms",
    location: "Kigali",
    rating: 4.6,
    reviews: 87,
    sold: 120,
    inStock: true,
    isNew: true,
    discount: 17,
    description: "Juicy mangoes, perfect for desserts, smoothies, or fresh fruit salads."
  },
  {
    id: 5,
    name: "Fresh Maize",
    category: "Grains",
    price: 300,
    originalPrice: 350,
    unit: "per Sack",
    image: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&q=80&w=600",
    seller: "John's Farm",
    location: "Kigali",
    rating: 4.8,
    reviews: 124,
    sold: 89,
    inStock: true,
    isNew: false,
    discount: 14,
    description: "High-quality maize, perfect for milling or cooking as fresh corn dishes."
  },
  {
    id: 6,
    name: "Fresh Beans",
    category: "Grains",
    price: 800,
    originalPrice: 950,
    unit: "per Sack",
    image: "https://images.unsplash.com/photo-1589994160734-c8838c600e4f?auto=format&fit=crop&q=80&w=600",
    seller: "Peter's Agro",
    location: "Huye",
    rating: 4.6,
    reviews: 67,
    sold: 45,
    inStock: true,
    isNew: false,
    discount: 16,
    description: "Nutritious beans, carefully harvested to ensure maximum freshness and flavor."
  },
  {
    id: 7,
    name: "Handheld Seeder",
    category: "Equipment",
    price: 15000,
    originalPrice: 18000,
    unit: "each",
    image: "https://images.unsplash.com/photo-1616627890457-923ae2f8c5c7?auto=format&fit=crop&q=80&w=600",
    seller: "Agro Tools Ltd",
    location: "Kigali",
    rating: 4.4,
    reviews: 55,
    sold: 12,
    inStock: true,
    isNew: true,
    discount: 17,
    description: "Easy-to-use handheld seeder for small farms and garden plots."
  },
  {
    id: 8,
    name: "Irrigation Pump",
    category: "Equipment",
    price: 75000,
    originalPrice: 80000,
    unit: "each",
    image: "https://images.unsplash.com/photo-1605792657667-08a1733ef3c6?auto=format&fit=crop&q=80&w=600",
    seller: "WaterFlow Supplies",
    location: "Huye",
    rating: 4.5,
    reviews: 38,
    sold: 7,
    inStock: false,
    isNew: false,
    discount: 6,
    description: "Reliable irrigation pump to water your crops efficiently."
  },
  {
    id: 9,
    name: "Tomato Seeds",
    category: "Seeds",
    price: 500,
    originalPrice: 500,
    unit: "per Pack",
    image: "https://images.unsplash.com/photo-1592928304187-5e0b0845c4f0?auto=format&fit=crop&q=80&w=600",
    seller: "Seed World",
    location: "Kigali",
    rating: 4.7,
    reviews: 28,
    sold: 102,
    inStock: true,
    isNew: false,
    discount: 0,
    description: "High-germination tomato seeds for your home or commercial garden."
  },
  {
    id: 10,
    name: "Maize Seeds",
    category: "Seeds",
    price: 600,
    originalPrice: 700,
    unit: "per Pack",
    image: "https://images.unsplash.com/photo-1596496057533-6b24f3d7f5b5?auto=format&fit=crop&q=80&w=600",
    seller: "Seed World",
    location: "Rubavu",
    rating: 4.6,
    reviews: 34,
    sold: 78,
    inStock: true,
    isNew: true,
    discount: 14,
    description: "Premium maize seeds to yield strong and healthy crops."
  },
  {
    id: 11,
    name: "Live Chickens",
    category: "Livestock",
    price: 700,
    originalPrice: 850,
    unit: "per Chicken",
    image: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&q=80&w=600",
    seller: "Emma's Poultry",
    location: "Kigali",
    rating: 4.5,
    reviews: 43,
    sold: 67,
    inStock: false,
    isNew: false,
    discount: 18,
    description: "Healthy live chickens for your farm or personal poultry needs."
  },
  {
    id: 12,
    name: "Goat Kids",
    category: "Livestock",
    price: 25000,
    originalPrice: 28000,
    unit: "per Goat",
    image: "https://images.unsplash.com/photo-1616446138676-2d38ad6f2f4f?auto=format&fit=crop&q=80&w=600",
    seller: "Mountain Livestock",
    location: "Huye",
    rating: 4.6,
    reviews: 22,
    sold: 15,
    inStock: true,
    isNew: true,
    discount: 10,
    description: "Young goats, healthy and vaccinated, perfect for breeding or farming."
  }
];

export default products;
